#:schema node_modules/wrangler/config-schema.json
name = "scoreboard-web"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat"]

# This is the modern way to serve Next.js static assets in a Worker
[assets]
directory = ".open-next/assets"
binding = "ASSETS"git

[vars]
# Values here are used as defaults. 
# GitHub Secrets will override these during production builds.
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "8714a068f13740d2a2aa5135c14c0f2b"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "scoreboard-web" # Must match your 'name' at the top